server:
    port: 8601

spring:
    application:
        name: DURAN-CATASTRO-SERVICES
    profiles:
        active: dev

    jpa:
        database: POSTGRESQL
        show-sql: true
        properties:
            hibernate:
                default_schema: public
                ddl-auto: update
                temp:
                use_jdbc_metadata_defaults: false

    main:
        allow-bean-definition-overriding: true

    logging:
        level:
            org:
                springframework:
                    ws: TRACE
